on: [push]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 15.x
      uses: actions/setup-node@v2
      with:
        node-version: 15.x
    - name: Upload package artifact
      uses: actions/upload-artifact@v2
      with:
        name: Project-deploy
        path: docs/wonderland-casdk/1.0.0/
    - name: Install dependencies
      run: npm ci
    - name: Generate docs
      run: npm run docs

  deploy:
    needs: docs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Download package artifact
      uses: actions/download-artifact@v2
      with:
        name: Project-deploy
        path: deploy
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.1.1
      with:
        branch: gh-pages
        folder: docs/wonderland-casdk/1.0.0
